### ISSUE TITLE
Add Docker-Compose Support

### ISSUE THREAD

**Issue by Adron** [Adron/twitz#12]
Tweak the existing "Docker" setup so that docker-compose can be used to bring up the environment and bring down the environment.

**Comment by kuskoman** [comment]
Seems like creating external docker network in docker compose is not possible https://stackoverflow.com/questions/44147002/can-i-use-docker-compose-to-create-networks-without-containers and I dont want to dockerize "whole" project, because it would have more cons than pros (since it's console application, creating separate container for it makes a lot of difficulties, like running every command within docker run command)

**Comment by Adron** [comment]
Ah, the network doesn't really need created as long as there's a set IP we could get for the container to run with. The idea with the IP is being about to automate connecting to it and also to prospectively add more nodes to the cluster. So maybe docker-compose could startup the single container node of the Cassandra instance and just get an IP assigned to it somehow?

**Comment by Adron** [comment]
Thanks @kuskoman for taking care of that, good job! :metal:
